#!/usr/bin/env bash
# Emit the Homebrew formula for a released tag, on stdout.
#
#   ./scripts/formula.sh v0.1.2 > ../homebrew-tap/Formula/podrick.rb
#
# The checksums are read off the published assets rather than off a local build, so the
# formula can only ever describe what someone would actually download.
set -euo pipefail

tag="${1:-}"
if [ -z "$tag" ]; then
    echo "usage: $0 <tag>   (e.g. v0.1.2)" >&2
    exit 2
fi
version="${tag#v}"
base="https://github.com/aram-p/podrick/releases/download/$tag"

sha() {
    curl -fsSL "$base/pd-$1.tar.gz" | shasum -a 256 | cut -d' ' -f1
}

mac_arm=$(sha aarch64-apple-darwin)
mac_x86=$(sha x86_64-apple-darwin)
linux_arm=$(sha aarch64-unknown-linux-gnu)
linux_x86=$(sha x86_64-unknown-linux-gnu)

cat <<EOF
# Generated by scripts/formula.sh in aram-p/podrick. Do not hand-edit.
class Podrick < Formula
  desc "Terminal task tracker with a perfect memory, built for agents first"
  homepage "https://github.com/aram-p/podrick"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/pd-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/pd-x86_64-apple-darwin.tar.gz"
      sha256 "$mac_x86"
    end
  end

  on_linux do
    on_arm do
      url "$base/pd-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/pd-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
  end

  def install
    bin.install "pd"
  end

  test do
    # Exercises a write and a read against a throwaway file, so a broken binary fails
    # here rather than the first time someone runs it.
    system bin/"pd", "--file", "list.podrick", "add", "it works"
    assert_match "it works", shell_output("#{bin}/pd --file list.podrick list")
    assert_match "pd $version", shell_output("#{bin}/pd --version")
  end
end
EOF
